apiVersion: apps/v1
kind: Deployment 
metadata:
  name: postgres-mws
  namespace: bpms-load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mws
  template:
    metadata:
      labels:
        app: postgres-mws
    spec:
      containers:
        - name: postgres-mws
          image: registry-144fd7c1.nip.io/v2/postgres:14.8
          imagePullPolicy: Always
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: postgres-secret-mws # Using the ConfigMap postgres-secret
      imagePullSecrets:
          - name: container-image-registry-creds