apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-cluster-ip-svc-mws # Sets the service name
  namespace: bpms-load-test
  labels:
    app: postgres-mws # Defines app to create service for
spec:
  type: ClusterIP # Sets the service type
  ports:
    - port: 5432 # Sets the port to run the postgres application
  selector:
    app: postgres-mws