---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: bpm-demo-my-project-configmap-prt-settings
      namespace: bpms-load-test
    data:
      prt.cnf: |
        #
        #Fri May 12 14:52:59 SGT 2023
        watt.prt.processExpire=60
        watt.prt.sleepInterval=1
        watt.prt.checkDuplicates=false
        watt.prt.uploadMetadata=true
        watt.prt.maxBroadcastEvents=1000
        watt.prt.failedProcessExpire=3600
        watt.prt.maxdbretries=360
        watt.prt.externalcluster=true
        watt.prt.reap.invokeas=Administrator
        watt.prt.auditLogProcessAtRest=false
        watt.prt.cleanInterval=600
        watt.prt.transport.default=webMethods Messsaging
        watt.prt.broadcastInterval=120
        watt.prt.optimizeBrokerURL=